version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"


  wp:
    build: .
    depends_on:
      - db
    volumes:
      - ./wp-data/wp-content:/var/www/html/wp-content/
    env_file: .env
    ports:
      - "${EXPOSED_PORT}:80"

  pma:
    image: phpmyadmin:latest
    ports:
      - "8800:80"
    env_file: .env